version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: tesis-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "tesis_db"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - tesis-db:/var/lib/postgresql/data
    networks:
      - thingsboard_default

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: tesis-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "12345678"
    depends_on:
      - db
    networks:
      - thingsboard_default

  api:
    image: nest-tb-api-app:latest
    restart: always
    container_name: tesis-api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    networks:
      - thingsboard_default

volumes:
  tesis-db:

networks:
  thingsboard_default:
    driver: bridge
    external: true
